name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: |
        git fetch --prune --unshallow
    - name: Yocto build
      uses: Jokymon/yocto-docker-repo-build-action@713f38ef7c190bfd3b0d658b420b7418c1e5cdf4
    - name: Save the artifact
      uses: actions/upload-artifact@v1
      with:
        name: raspberry3-image
        path: /github/workspace/build/tmp/deploy/images/raspberrypi3/core-image-minimal-raspberrypi3.rpi-sdimg
